export const NAME_SIGN_UP_FIELD_ID = 'nameSignUpFieldId';
export const EMAIL_SIGN_UP_FIELD_ID = 'emailSignUpFieldId';
export const EMAIL_SIGN_IN_FIELD_ID = 'emailSignInFieldId';
export const PASSWORD_SIGN_IN_FIELD_ID = 'passwordSignInFieldId';
export const PASSWORD_SIGN_IN_BUTTON_ID = 'passwordSignInButtonId';
export const SIGN_UP_AGREEMENTS_CHECKBOX_ID = 'signUpAgreementsCheckboxId';
export const SIGN_IN_BUTTON_ID = 'signInButtonId';
export const SIGN_UP_BUTTON_ID = 'signUpButtonId';
export const SIGN_IN_HEADER_ID = 'signInHeaderId';
export const SIGN_UP_HEADER_ID = 'signUpHeaderId';
export const SIGN_UP_SAVE_ACTIONS_ID = 'signUpSaveActionsId';
export const EMAIL_SIGN_IN_METHOD_BUTTON_ID = 'emailSignInMethodButton';
export const PASSWORD_SIGN_IN_METHOD_BUTTON_ID = 'passwordSignInMethodButton';
export const USER_SWITCH_ID = 'userSwitch';
export const SUCCESS_CONTENT_ID = 'successContent';
export const BACK_BUTTON_ID = 'backButtonId';
export const RESEND_EMAIL_BUTTON_ID = 'resendEmailButtonId';
export const buildMemberMenuItemId = (id: string) => `memberMenuItemId-${id}`;
