name: Cypress CI

# Control when the action will run
on:
  # Triggers the workflow on push events except for the main branch
  push:
    branches-ignore:
      - main

concurrency:
  group: cypress-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cypress:
    name: Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Yarn Install and Cache
        uses: graasp/graasp-deploy/.github/actions/yarn-install-and-cache@v1
        with:
          cypress: true

      # type check
      - name: Type-check code
        run: tsc --noEmit

      #  use the Cypress GitHub Action to run Cypress tests within the chrome browser
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install: false
          start: yarn dev
          browser: chrome
          quiet: true
          config-file: cypress.config.ts
          cache-key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        env:
          VITE_PORT: 3001
          VITE_GRAASP_DOMAIN: localhost
          VITE_GRAASP_API_HOST: http://localhost:3636
          VITE_GRAASP_AUTH_HOST: http://localhost:3001
          VITE_GRAASP_BUILDER_HOST: http://localhost:3111
          VITE_SHOW_NOTIFICATIONS: true

      # after the test run completes
      # store any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: coverage report
        run: npx nyc report --reporter=text-summary
