name: Cypress CI

on:
  push:
    branches:
      - main
  merge_group:
  pull_request:

concurrency:
  group: cypress-${{ github.ref }}
  cancel-in-progress: false

jobs:
  cypress:
    name: Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Yarn Install and Cache
        uses: graasp/graasp-deploy/.github/actions/yarn-install-and-cache@v1
        with:
          cypress: true

      # type check
      - name: Check code
        run: yarn check

      #  use the Cypress GitHub Action to run Cypress tests within the chrome browser
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install: false
          build: yarn build:test
          start: yarn preview:test
          browser: chrome
          quiet: true
          config-file: cypress.config.ts
          cache-key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        env:
          VITE_PORT: ${{ vars.VITE_PORT }}
          VITE_VERSION: ${{ vars.VITE_VERSION }}
          VITE_GRAASP_DOMAIN: ${{ vars.VITE_GRAASP_DOMAIN }}
          VITE_GRAASP_API_HOST: ${{ vars.VITE_GRAASP_API_HOST }}
          VITE_GRAASP_BUILDER_HOST: ${{ vars.VITE_GRAASP_BUILDER_HOST }}
          VITE_SHOW_NOTIFICATIONS: ${{ vars.VITE_SHOW_NOTIFICATIONS }}
          VITE_RECAPTCHA_SITE_KEY: ${{ secrets.VITE_RECAPTCHA_SITE_KEY }}
          VITE_DEFAULT_REDIRECTION_URL: ${{ vars.VITE_DEFAULT_REDIRECTION_URL }}

      # after the test run completes
      # store any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: coverage report
        run: npx nyc report --reporter=text-summary
